[[redirects]]
  from = "/"
  to = "https://webflow.voicebar.co"
  status = 200
  force = true

[[redirects]]
  from = "/signup"
  to = "https://voicebar.typeform.com/to/NUynD2GT"
  status = 301

[[redirects]]
  from = "/feedback"
  to = "https://voicebar.typeform.com/to/aryQh6Da"
  status = 301

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
