[[redirects]]
  from = "/"
  to = "https://webflow.storydating.com"
  status = 200
  force = true

[[redirects]]
  from = "/efficient"
  to = "https://webflow.storydating.com/efficient"
  status = 200
  force = true

[[redirects]]
  from = "/efficient/join"
  to = "https://storydating.typeform.com/to/tgfN9WPN"
  status = 301

[[redirects]]
  from = "/join"
  to = "https://storydating.typeform.com/to/ocxmmOHo"
  status = 301

[[redirects]]
  from = "/signup"
  to = "https://storydating.typeform.com/to/ocxmmOHo"
  status = 301

[[redirects]]
  from = "/rate"
  to = "https://storydating.typeform.com/to/IZwuDEu0"
  status = 301

[[redirects]]
  from = "/prefs"
  to = "https://storydating.typeform.com/to/lOJkjvuS"
  status = 301

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
