[[redirects]]
  from = "/"
  to = "https://webflow.storydating.com"
  status = 200
  force = true

[[redirects]]
  from = "/join"
  to = "https://datwct.typeform.com/to/ocxmmOHo"
  status = 301

[[redirects]]
  from = "/feedback"
  to = "https://datwct.typeform.com/to/WtT4fdmX"
  status = 301

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
