[[redirects]]
  from = "https://story.dating/*"
  to = "https://storydating.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/"
  to = "https://webflow.storydating.com"
  status = 200
  force = true

[[redirects]]
  from = "/referral"
  to = "https://webflow.storydating.com/referral"
  status = 200
  force = true

[[redirects]]
  from = "/r"
  to = "https://webflow.storydating.com/referral"
  status = 200
  force = true

[[redirects]]
  from = "/weekly"
  to = "https://form.typeform.com/to/Squ29w7E"
  status = 301

[[redirects]]
  from = "/rate"
  to = "https://storydating.typeform.com/to/Qrb9ZgUh"
  status = 301

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
