[[redirects]]
  from = "/"
  to = "https://webflow.voicebar.co"
  status = 200
  force = true

[[redirects]]
  from = "/signup"
  to = "https://voicebar.typeform.com/to/NUynD2GT?r=:r"
  status = 301
  query = {r = ":r"}

[[redirects]]
  from = "/feedback"
  to = "https://voicebar.typeform.com/to/aryQh6Da?u=:u&m=:m"
  status = 301
  query = {u = ":u", m = ":m"}

[[redirects]]
  from = "/prefs"
  to = "https://voicebar.typeform.com/to/dDndU0sf?user=:user"
  status = 301
  query = {user = ":user"}

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
