[[redirects]]
  from = "/"
  to = "https://webflow.storydating.com"
  status = 200
  force = true

[[redirects]]
  from = "/join"
  to = "https://storydating.typeform.com/to/ocxmmOHo"
  status = 301

[[redirects]]
  from = "/signup"
  to = "https://storydating.typeform.com/to/ocxmmOHo"
  status = 301

[[redirects]]
  from = "/rate"
  to = "https://storydating.typeform.com/to/WtT4fdmX"
  status = 301

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
