name: Deploy to prod
on: 
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: functions
    env:
      PROD_FIREBASE_TOKEN: ${{ secrets.PROD_FIREBASE_TOKEN }}
    strategy:
      matrix:
        node-version: [10.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn
    - run: npm install -g firebase-tools@8.11.2
    - run: firebase deploy --only functions --token "$PROD_FIREBASE_TOKEN" -P prod
    - run: curl -X POST -d {} https://api.netlify.com/build_hooks/6068e0e7892b9480a347a2b6
