name: Deploy to dev
on: 
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: functions
    env:
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
    strategy:
      matrix:
        node-version: [10.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn
    - run: npm install -g firebase-tools@8.11.2
    - run: firebase deploy --only functions --token "$FIREBASE_TOKEN" -P default